name: Despliegue a GitHub Pages (Oficial)

# Permisos mínimos requeridos para la acción
permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches: ["main"]

# Permite que solo una acción se ejecute a la vez
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  # 1. Construcción (Build)
  # Prepara los archivos para el despliegue.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        
      - name: Configuración del entorno de Pages (Requerido)
        uses: actions/configure-pages@v4

      - name: Subir Artifactos de Despliegue
        uses: actions/upload-pages-artifact@v3
        with:
          # PUBLICAR TODO EL CONTENIDO DEL REPOSITORIO (incluyendo 1, 2, 3...)
          path: './' 

  # 2. Despliegue (Deployment)
  # Publica el artefacto subido a GitHub Pages.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
