# .github/workflows/deploy.yml

name: Despliegue Autom치tico

# Otorga permisos de escritura al token para que la acci칩n de despliegue
# pueda crear la rama gh-pages o subir archivos.
permissions:
  contents: write

# El workflow se activa con cada push a la rama 'main'
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Descarga tu c칩digo
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      
      # Paso 2: Despliegue a GitHub Pages
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          # RUTA DE LA CARPETA:
          # Usamos './' para subir TODO el contenido del repositorio (incluyendo carpetas 1, 2, 3...)
          publish_dir: ./ 
          
          # Fuerza el push a la rama 'gh-pages', necesaria para la configuraci칩n est치ndar.
          force_orphan: true
```
eof

---

## 游눠 Pasos Finales para Arreglar la Pantalla en Blanco

La correcci칩n del `deploy.yml` asegura que se suban todas las carpetas. Ahora, para arreglar la **pantalla en blanco**, tienes que asegurarte de que tu **`index.html`** de la ra칤z tenga contenido **visible** (el c칩digo del men칰).

1.  **Reemplaza** el contenido de tu archivo **`.github/workflows/deploy.yml`** con el c칩digo limpio de arriba.
2.  **Verifica el `index.html`:** Aseg칰rate de que el archivo **`index.html`** en la **ra칤z** de tu proyecto contenga el c칩digo del men칰 o alg칰n texto visible, como te suger칤 anteriormente.
3.  **Guarda** ambos archivos.
4.  **Ejecuta los comandos** en la terminal de VS Code:

```bash
git add .
git commit -m "Fix: Limpieza del deploy.yml y verificacion de contenido de index.html"
git push