# .github/workflows/deploy.yml

name: Despliegue Automático

# ------------------------------
# 1. PERMISOS
# Se requiere permiso de 'contents: write' para que la acción de despliegue
# pueda crear la rama gh-pages o subir archivos a la rama principal.
# ------------------------------
permissions:
  contents: write

# ------------------------------
# 2. DISPARADOR (TRIGGER)
# Define que este flujo de trabajo se ejecuta cada vez que hay un push
# a la rama 'main' (o la rama principal de tu proyecto).
# ------------------------------
on:
  push:
    branches:
      - main 

# ------------------------------
# 3. TRABAJOS (JOBS)
# El trabajo que se encarga del despliegue.
# ------------------------------
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Paso A: Descarga tu código
      - name: Checkout del repositorio
        uses: actions/checkout@v4
      
      # ----------------------------------------------------------------
      # Paso B (OPCIONAL): Construcción del proyecto
      # DESCOMENTA esta sección si tu proyecto necesita ser compilado (ej. React, Vue).
      # Si es solo HTML/CSS/JS puro, déjala COMENTADA.
      # ----------------------------------------------------------------
      #- name: Configurar Node.js (Si usas JS avanzado/frameworks)
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: '20' # O la versión que uses
      #- name: Instalar dependencias
      #  run: npm install
      #- name: Construir proyecto
      #  run: npm run build
        
      # ----------------------------------------------------------------
      # Paso C: Despliegue a GitHub Pages
      # ----------------------------------------------------------------
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # RUTA DE LA CARPETA:
          # Si NO usaste el Paso B, usa './' (la raíz del proyecto)
          # Si SÍ usaste el Paso B (build), usa la carpeta de salida (ej. './build' o './dist')
          publish_dir: ./ 
          # Fuerza el push a la rama 'gh-pages', necesaria para la configuración estándar.
          force_orphan: true